const drugs=[
{name:"Metformin",class:"Biguanide antidiabetic",atc:"A10BA02",uses:["Type 2 diabetes mellitus"],effects:["Nausea","Diarrhea","Abdominal discomfort"],serious:["Lactic acidosis — rare"]},
{name:"Lisinopril",class:"ACE inhibitor",atc:"C09AA03",uses:["Hypertension","Heart failure"],effects:["Cough","Dizziness","Hyperkalemia"],serious:["Angioedema"]},
{name:"Amlodipine",class:"Calcium-channel blocker",atc:"C08CA01",uses:["Hypertension","Angina"],effects:["Peripheral edema","Headache","Flushing"],serious:["Severe hypotension — uncommon"]},
{name:"Atorvastatin",class:"HMG-CoA reductase inhibitor",atc:"C10AA05",uses:["Hypercholesterolemia","Cardiovascular risk reduction"],effects:["Muscle pain","Headache","GI symptoms"],serious:["Myopathy/rhabdomyolysis — rare"]},
{name:"Amoxicillin",class:"Penicillin antibacterial",atc:"J01CA04",uses:["Susceptible bacterial infections"],effects:["Nausea","Diarrhea","Rash"],serious:["Anaphylaxis","Severe cutaneous reactions — rare"]},
{name:"Losartan",class:"Angiotensin II receptor blocker",atc:"C09CA01",uses:["Hypertension","Diabetic kidney disease"],effects:["Dizziness","Hyperkalemia"],serious:["Angioedema — uncommon"]},
{name:"Omeprazole",class:"Proton-pump inhibitor",atc:"A02BC01",uses:["GERD","Peptic ulcer disease"],effects:["Headache","Abdominal pain","Diarrhea"],serious:["C. difficile-associated diarrhea; hypomagnesemia with prolonged use"]},
{name:"Levothyroxine",class:"Thyroid hormone",atc:"H03AA01",uses:["Hypothyroidism"],effects:["Palpitations if over-replaced","Tremor","Insomnia"],serious:["Arrhythmias from excessive dosing"]},
{name:"Insulin glargine",class:"Long-acting insulin",atc:"A10AE04",uses:["Diabetes mellitus"],effects:["Hypoglycemia","Injection-site reactions"],serious:["Severe hypoglycemia"]}
];
const meds={heparin:{on:74,forecast:34,lead:5,risk:"High",action:"Review purchase order"},vanco:{on:185,forecast:37,lead:5,risk:"Moderate",action:"Increase replenishment review"},amox:{on:1240,forecast:88,lead:4,risk:"Low",action:"No immediate order"},insulin:{on:420,forecast:5.8,lead:3,risk:"Moderate",action:"Prioritize FEFO / review expiry exposure"},cef:{on:96,forecast:21,lead:5,risk:"Moderate",action:"Review replenishment"}};
let submissions=JSON.parse(localStorage.getItem("pharmaSubmissions")||"[]");
function renderDrugs(list){document.getElementById("drugResults").innerHTML=list.map(d=>`<article class="drug"><h3>${d.name}</h3><div class="class">${d.class} · ATC ${d.atc}</div><h4>Therapeutic uses</h4><p>${d.uses.join(" · ")}</p><h4>Common adverse effects</h4><p>${d.effects.join(" · ")}</p><h4>Important / serious effects</h4><p>${d.serious.join(" · ")}</p></article>`).join("")||'<div class="card"><b>No demonstration record found.</b><p class="muted">The production version can connect to a larger authoritative drug dataset.</p></div>'}
function searchDrugs(){const q=document.getElementById("drugSearch").value.toLowerCase().trim();renderDrugs(q?drugs.filter(d=>(d.name+" "+d.class+" "+d.uses+" "+d.effects).toLowerCase().includes(q)):drugs);document.getElementById("drugs").scrollIntoView({behavior:"smooth"})}
function focusDrug(){document.getElementById("drugs").scrollIntoView({behavior:"smooth"});setTimeout(()=>document.getElementById("drugSearch").focus(),500)}
function analyze(){const m=meds[document.getElementById("med").value],cover=(m.on/m.forecast).toFixed(1),after=Math.max(0,m.on-m.forecast*m.lead),order=Math.max(0,Math.ceil(m.forecast*(m.lead+14)-m.on));document.getElementById("analysis").innerHTML=`<div class="metrics"><div class="metric"><span class="muted">On hand</span><br><b>${m.on}</b></div><div class="metric"><span class="muted">Forecast/day</span><br><b>${m.forecast}</b></div><div class="metric"><span class="muted">Days of cover</span><br><b>${cover}</b></div><div class="metric"><span class="muted">After lead time</span><br><b>${after.toFixed(0)}</b></div></div><div class="callout"><b>${m.action}</b><br>Risk: ${m.risk} • Example review quantity: ${order} units.<br>Human review is required before procurement action.</div>`}
function openPortal(){document.getElementById("portal").classList.add("show");document.body.style.overflow="hidden";renderSubmissions()}
function closePortal(){document.getElementById("portal").classList.remove("show");document.body.style.overflow=""}
function portalTab(name,btn){document.querySelectorAll(".portal-tabs button").forEach(x=>x.classList.remove("active"));btn.classList.add("active");document.querySelectorAll(".portal-pane").forEach(x=>x.classList.add("hidden"));document.getElementById("portal-"+name).classList.remove("hidden");if(name==="submissions")renderSubmissions()}
function submitMedicine(e){e.preventDefault();const item={id:Date.now(),company:document.getElementById("company").value,generic:document.getElementById("generic").value,brand:document.getElementById("brand").value,atc:document.getElementById("atc").value,date:new Date().toLocaleDateString(),status:"Pending Review"};submissions.unshift(item);localStorage.setItem("pharmaSubmissions",JSON.stringify(submissions));e.target.reset();alert("Submission received in the prototype. It is now marked Pending Review.");renderSubmissions()}
function renderSubmissions(){const box=document.getElementById("submissionList");box.innerHTML=submissions.length?submissions.map(s=>`<div class="submission"><span class="status">${s.status}</span><b>${s.generic}${s.brand?" ("+s.brand+")":""}</b><span>${s.company} • ATC ${s.atc||"Not provided"} • Submitted ${s.date}</span></div>`).join(""):'<p class="muted">No submissions yet. Add a medicine to create a demo submission.</p>'}
document.getElementById("drugSearch").addEventListener("keydown",e=>{if(e.key==="Enter")searchDrugs()});
document.getElementById("portal").addEventListener("click",e=>{if(e.target.id==="portal")closePortal()});
const vals=[42,48,44,55,61,57,66,63,72,68,75,79,74,83,87,82,90,86,94,91,98,102,96,108,111,105,116,121,114,126];
document.getElementById("chart").innerHTML=vals.map(v=>`<div class="bar" style="height:${Math.min(95,v/1.35)}%"></div>`).join("");
renderDrugs(drugs);analyze();
